### ISSUE TITLE
Error when running larger numbers of cells from the same dataset

### ISSUE THREAD

**Issue by symbiologist** [ncborcherding/Trex#3]
Hi Nicholas,

Love the work you're doing in the TCR space. I'm trying to run the Trex pipeline on a dataset of my own and encountering an issue.

Here's my code:
```
seuratobj <- RunUMAP(seuratobj, 
                     reduction = "Trex.KF",
                     dims = 1:30,
                     reduction.name = 'Trex.umap', 
                     reduction.key = 'trexUMAP_')
```
Here's the output:

```
[1] "Calculating the Amino Acid Properties..."
Error in rep(NA, 50 - length(refer)) : invalid 'times' argument
```

The dataset is ~15k cells with TCR data. I don't encounter this issue running the example dataset from your vignette. Strangely, I don't encounter this issue if I downsample my data to 7500 cells, making me think it's not an problem with the data but something to do with the number of input cells. What do you think? 

Best,
David

**Comment by ncborcherding** [comment]
Hey David, 

Thanks for reaching out - I have seen this exact error before. It is in fact due to have a chain that is longer than 50 amino acids in length (which is the amount of zero padding I had for the models). This is why you don't encounter any issues if you sub sampled (likely you have removed the chain > 50 aa). 

Couple of options: 

**1. Remove any cell with amino acid length > 50**

```
cells.to.remove <- unique(c(which(nchar(stringr::str_split(seuratobj$CTaa, "_", simplify = TRUE)[,1]) > 50), #TRA chain > 50 aa
                     which(nchar(stringr::str_split(seuratobj$CTaa, "_", simplify = TRUE)[,2]) > 50))) # TRB chain > 50 aa residues

if(length(cells.to.remove) > 0) {
    cells <- rownames(list[[]])
    cells <- cells[-cells.to.remove]
    seuratobj <- subset(seuratobj, cells = cells)
}
```

**2. Install the Dev Version**
The dev version has more comprehensive models that I used 60 aa redisudes for zero padding
```
devtools::install_github("ncborcherding/Trex@dev")
```

I will also add to my to-do list to give a unit test and warning if this occurs, so in the future users won't have to guess at that cryptic warning. Thanks for reaching out and let me know if you need anything else. 

Nick
